services:
  gothello_web:
    container_name: php_container
    image: php:8.3-apache
    volumes:
      - '../..:/var/www/html'
    ports:
      - '8080:80'
    command:  >
      bash -c "chown www-data /var/www/html/games &&
      chown www-data /var/www/html/games/free &&
      chown www-data /var/www/html/games/private &&
      apache2-foreground"